version: "3.5"

services:
  consul:
    image: consul
    container_name: consul
    restart: unless-stopped
    network_mode: host

  traefik:
    image: traefik:v2.3
    container_name: traefik
    restart: unless-stopped
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./host-traefik/traefik.yml:/traefik.yml:ro

  fabio:
    image: fabiolb/fabio
    container_name: fabio
    restart: unless-stopped
    environment:
      - FABIO_REGISTRY_CONSUL_ADDR=localhost:8500
    network_mode: host

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    network_mode: host

  influxdb:
    image: influxdb
    container_name: influxdb
    restart: unless-stopped
    network_mode: host